name: Build Docker Images
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build project
        run: mvn clean install -Pdocker -Ddocker.skip-test=true -pl -jmxterm

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: base
          file: base/Dockerfile.ubi8
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thinkportgmbh/confluentinc/cp-base-new:ubi8-latest
          build-args: |
            ARTIFACT_ID=cp-base-new
            PROJECT_VERSION=7.0.1

