name: Build Docker Images
on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build project
        run: mvn clean install

      - name: Build Docker image
        run: docker buildx build --platform linux/aarch64,linux/amd64 -f base/Dockerfile.ubi8 --build-arg ARTIFACT_ID=cp-base-new --build-arg PROJECT_VERSION=7.0.1 base/